[package]
name = "rotation3"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = { version = "0.32.6", features = ["serde-serialize"] }
num-traits = "0.2.19"
serde = { version = "1.0.203", features = ["derive"] }

[dev-dependencies]
approx = "0.5.1"
